development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bobgzthyivirpw:8f0f68b75f483b3ff3c2bbab6dba71e68b081d5b5181bd59b4511cc4b74a3b68@ec2-50-17-206-214.compute-1.amazonaws.com:5432/d2d662hbpl0vf1
  # url: redis://localhost:6379/1
  channel_prefix: DjGear_production
